### ISSUE TITLE
FR: Game trophy percentage attribute

### ISSUE THREAD

**Issue by SeanPM5** [JackJPowell/hass-psn#11]
I'm trying to replicate the PS5 dashboard UI where it says "15/48 trophies, 21% progress" for specific games. I figured out the first part by creating the following template sensor:

```
template:
  - sensor:
      - name: "Username Game Trophies"
        unique_id: username_game_trophies
        icon: mdi:sony-playstation
        availability: >
          {{ is_state('sensor.username_status', 'Playing') }}
        state: >
          {% set earned_trophies = state_attr('sensor.username_status', 'earned_trophies') %}
          {% set trophies = state_attr('sensor.username_status', 'trophies') %}

          {% set earned = earned_trophies.bronze + earned_trophies.silver + earned_trophies.gold + earned_trophies.platinum %}
          {% set total = trophies.bronze + trophies.silver + trophies.gold + trophies.platinum %}

          {{ earned }} / {{ total }}
```

I was hoping I could use this to calculate the current games trophy progress too -- divide earned trophies by total number of trophies, then multiply by 100 to convert it to percentage. That calculation comes out to 31% however while the PS5 dashboard is telling me only 21% for that particular game (God of War Ragnarok).

I'm guessing that Sony probably weights the various trophy tiers (platinum, gold, silver, bronze) differently but I have no idea what criteria they use. Was wondering if perhaps this information is available and can be added as an attribute on the "Status" sensor, much like the trophy level sensor has a "Next Level Progress" attribute?

There's also another "Game Progress" number too I see on the dashboard that would be interesting to have as part of this sensor if it's possible to retrieve?

![IMG_1989](https://github.com/user-attachments/assets/019653a3-d6fa-46d7-9867-3c7a34837292)

**Comment by JackJPowell** [comment]
Hey @SeanPM5, 

I never noticed this before, but you're totally right! It looks like Sony is applying weights to the trophies when calculating the percentage. Lucky for us they include this percentage in the api response. I need to dig a bit more to see if the game progress is available but at the moment it's not looking like it. I'll try and have this update out later today. 

![Screenshot 2024-08-04 at 11 07 07 AM](https://github.com/user-attachments/assets/42429b1b-4441-4e0b-904d-9cba52c1a474)

**Comment by JackJPowell** [comment]
Hey @SeanPM5, I had a beta release out yesterday afternoon and just now pushed it out to everyone. Enjoy.

**Comment by SeanPM5** [comment]
Thanks so much @JackJPowell , that was the last big missing piece for me. Glad this information was available, hopefully Sony includes the game progress number in the API at some point too.

Gotta tweak the visuals a bunch, but have the progress bar similar to the PS5 dashboard now (using [bar-card](https://github.com/custom-cards/bar-card)). Thanks again.

<img width="527" alt="Screenshot 2024-08-05 at 7 04 52 PM" src="https://github.com/user-attachments/assets/53767e05-7afa-45c4-800e-8157762b2ea2">

**Comment by xXREDXIIIIXx** [comment]
I know you already have this update out, just wanted to enlighten you all with the weight information, back when I was using the API around 10+ years ago, it was determined that the trophies were given point values.

- B = 15 pts
- S = 30 pts
- G = 90 pts
- P = 180 pts (its now worth 300 pts!)

As an example with the Astro's playroom post above 

- Gold: 360 / 450 pts
- Silver: 390 / 420 pts
- Bronze: 405 / 465 pts
- Total Points: 1155 / 1335 pts

1155 divided by 1335 = 0.865 or 86% as they rounded down. 
The Platinum point value is not used in determining the value as its only obtained after you get 100%

Sorry if this opens the topic again
