### ISSUE TITLE
HA 2024.11.0b1 - Integration does not start

### ISSUE THREAD

**Issue by Thrasher2020** [JackJPowell/hass-psn#16]
**Describe the bug**
Does not start and gives this error : 

`Logger: homeassistant.setup
Source: setup.py:269
First occurred: 16:34:48 (1 occurrences)
Last logged: 16:34:48

Setup failed for custom integration 'playstation_network': Requirements for playstation_network not found: ['PSNAWP-HA==2.1.0'].`

`Logger: homeassistant.util.package
Source: util/package.py:152
First occurred: 16:34:47 (3 occurrences)
Last logged: 16:34:48

Unable to install package PSNAWP-HA==2.1.0: × No solution found when resolving dependencies: ╰─▶ Because psnawp-ha==2.1.0 depends on attrs==23.2.0 and attrs==24.2.0, we can conclude that psnawp-ha==2.1.0 cannot be used. And because you require psnawp-ha==2.1.0, we can conclude that your requirements are unsatisfiable.`

**Comment by JackJPowell** [comment]
Thanks @Thrasher2020! Fixed in release 0.5.2
https://github.com/JackJPowell/hass-psn/releases/tag/v0.5.2
