### ISSUE TITLE
HA 2024.11

### ISSUE THREAD

**Issue by larsoss** [JackJPowell/hass-psn#17]
Logger: homeassistant.setup
Bron: setup.py:269
Eerst voorgekomen: 17:55:42 (2 gebeurtenissen)
Laatst gelogd: 17:56:20

Setup failed for custom integration 'playstation_network': Requirements for playstation_network not found: ['PSNAWP-HA==2.1.0'].
Setup failed for 'default_config': Could not setup dependencies: go2rtc

Error. Things are change from home assistant update 2024.11b1

**Comment by JackJPowell** [comment]
Thanks. Update to release v0.5.3 for the fix.
