### ISSUE TITLE
Support for Regional Game Ratings

### ISSUE THREAD

**Issue by Levtos** [JackJPowell/hass-psn#21]
Hey @JackJPowell ,

I’ve noticed that game ratings are shown according to North American _ESRB_ standards by default, even though I’m connecting with a German PSN account. This means the ratings aren’t as relevant for users in other regions, like Germany, where _USK_ ratings are the standard.

When logging in through the German PlayStation site, the URL often includes what looks like “ca” (possibly for Canada). 
`https://ca.account.sony.com/api/v1/ssocookie`

I’ve tried changing the region code to “de”. "deDE" or “eu,” but it doesn’t seem to work, and game descriptions also stay in English.

I’m not entirely sure if this is a bug or a feature request—it could go either way. It seems like there might be an issue with the authentication flow defaulting to an international setup, pulling in North American _ESRB_ ratings rather than the correct regional ratings.

After doing a bit of research, I found other regional rating organizations that might be useful to support as well, like USK (Germany), PEGI (Europe) and CERO (Asia). Could we get worldwide support for regional game rating systems or a way to specify the region during setup? This would make things more accurate and relevant for users around the world.

**Comment by JackJPowell** [comment]
Hey @Levtos, if you would, give Beta 2 a shot and let me know if you see region appropriate information. I'm attempting to pull your home assistant country/language to pass to PSN but I'm not confident it's working. The docs say this information is on the hass.config object (and it is) but when I change my default language from english, the values there aren't updated. 

I also added support for downloading diagnostics. If you select that and take a look at the file that is downloaded you'll see a country and language entry at the very bottom. Could you tell me what yours says after updating to Beta 2? Thanks man!

![Screenshot 2024-11-09 at 1 21 55 PM](https://github.com/user-attachments/assets/d8fd8c09-09d1-406e-9cdd-fae57b261775)
![Screenshot 2024-11-10 at 9 02 52 AM](https://github.com/user-attachments/assets/51979882-2a5d-47da-9ecd-efbdbfcb3d6a)
