### ISSUE TITLE
Not sure if me, or they are getting hammered for the link for NPSSO

### ISSUE THREAD

**Issue by Node815** [JackJPowell/hass-psn#5]
I get a HTTP 429 Too many requests error.   I do have the ps5_mqtt addon which never really did much for me and I can remove it, but not sure if that's it.  Also have two mobile phones logged into the account.  During your development of this or testing encounter the same error?

**Comment by JackJPowell** [comment]
When I did get this error it was due to me not being logged into my PlayStation account in the same session when navigating to the npsso url. Are you sure you're logged in?

**Comment by Node815** [comment]
I made sure I was logged in, but got to thinking based on your reply, and logged out, cleared my cookies for the site, and then logged in and was able to get it to work, so it must have been a stale cookie from somewhere.

**Comment by xXREDXIIIIXx** [comment]
I had this issue yesterday also, seemed to be a login issue for me based on region, the link provided to login redirected me to the en-US site, once I figured that out, I switched to the en-GB site logged in at it worked instantly.

**Comment by JackJPowell** [comment]
@Node815, glad you that did the trick!

@xXREDXIIIIXx, do you happen to have the link handy? I would like to include it in the docs for others.

**Comment by xXREDXIIIIXx** [comment]
> @xXREDXIIIIXx, do you happen to have the link handy? I would like to include it in the docs for others.

Sure, The link I used is https://www.playstation.com/en-gb/ 

Needs testing but in my case I am from the UK and that is the the account login I registered with so it might just be that those from other countries just need to use their own region for the playstation.com login.

That being said... I just tested this again now, and I also hit the HTTP 429 Too many requests. so maybe I just got lucky? (but it did work the 1st time after changing the region) maybe you can check for yourself see if you also get the error to confirm?

**Comment by diego7marques** [comment]
Same strategy shared by @xXREDXIIIIXx worked for me. The steps I did:

1 - I logged out of my account
2 - Move to my region endpoint (https://www.playstation.com/pt-pt/)
3 - I logged in again

After that, the 429 error stopped and I was able to get the npsso token.

**Comment by JackJPowell** [comment]
I also was logged out a couple of hours ago. Seems like it may have been something on Sony's end. 
I've updated the readme to hopefully help people through some of these problems. Thanks guys!
